export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_LOGIN_FAILED = 'SHARED_LOGIN_FAILED';
export const SHARED_LOGIN_SUCCESS = 'SHARED_LOGIN_SUCCES';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';
export const SHARED_API_ERROR = 'SHARED_API_ERROR';
export const UPDATE_USERS = 'UPDATE_USERS';
export const ADD_USER = 'ADD_USER';


export const CHANNEL_UPDATE_CHANNEL = 'CHANNEL_UPDATE_CHANNEL';
export const CHANNEL_DELETE_CHANNEL = 'CHANNEL_DELETE_CHANNEL';
export const CHANNEL_LEAVE_CHANNEL = 'CHANNEL_LEAVE_CHANNEL';
export const CHANNEL_OPEN_CHANNEL = 'CHANNEL_OPEN_CHANNEL';
export const CHANNEL_OPEN_CHANNEL_CLOSE = 'CHANNEL_OPEN_CHANNEL_CLOSE';
export const CHANNEL_LOAD_MESSAGES = 'CHANNEL_LOAD_MESSAGES';
export const CHANNEL_OPEN_INVITING = 'CHANNEL_OPEN_INVITING';
export const CHANNEL_CANCEL_INVITING = 'CHANNEL_CANCEL_INVITING';
export const CHANNEL_UPDATE_EDITED_CHANNEL = 'CHANNEL_UPDATE_EDITED_CHANNEL';
export const CHANNEL_UPDATE_OPENED_CHANNEL = 'CHANNEL_UPDATE_OPENED_CHANNEL';
export const CHANNEL_CANCEL_EDITING_CHANNEL = 'CHANNEL_CANCEL_EDITING_CHANNEL';
export const CHANNEL_OPEN_EDITING_CHANNEL = 'CHANNEL_OPEN_EDITING_CHANNEL';
export const SET_ADD_CHANNEL_OPEN = 'SET_ADD_CHANNEL_OPEN';

export const MESSAGE_ADD_MESSAGE = 'MESSAGE_ADD_MESSAGE';
export const MESSAGE_DELETE_MESSAGE = 'MESSAGE_DELETE_MESSAGE';
export const MESSAGE_EDIT_MESSAGE = 'MESSAGE_EDIT_MESSAGE';

export const UPDATE_CHANNELS = 'UPDATE_CHANNELS';
export const ADD_CHANNEL = 'ADD_CHANNEL';

export const OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE';




export const PROFILE_UPDATE_DETAILS = 'PROFILE_UPDATE_DETAILS';
export const NOT_CHANGED = 'NOT_CHANGED';
export const INVALID = 'INVALID';
export const SAVEAVBLE = 'SAVEAVBLE';
export const SAVING_NOW = 'SAVING_NOW';



export const PROFILE_AVATAR_UPLOADING_STARTED = 'PROFILE_AVATAR_UPLOADING_STARTED';
export const PROFILE_AVATAR_UPLOADING_FAILED = 'PROFILE_AVATAR_UPLOADING_FAILED';
export const PROFILE_UPDATE_AVATAR = 'PROFILE_UPDATE_AVATAR';
export const PROFILE_AVATAR_FETCHING_STARTED = 'PROFILE_AVATAR_FETCHING_STARTED';
export const PROFILE_FETCHING_STARTED = 'PROFILE_FETCHING_STARTED';