export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';