export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_LOGIN_FAILED = 'SHARED_LOGIN_FAILED';
export const SHARED_LOGIN_SUCCESS = 'SHARED_LOGIN_SUCCES';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';
export const SHARED_API_ERROR = 'SHARED_API_ERROR';
export const UPDATE_USERS = 'UPDATE_USERS';


export const CHANNEL_UPDATE_CHANNEL = 'CHANNEL_UPDATE_CHANNEL';
export const CHANNEL_DELETE_CHANNEL = 'CHANNEL_DELETE_CHANNEL';
export const CHANNEL_CANCEL_EDITING_CHANNEL = 'CHANNEL_CANCEL_EDITING_CHANNEL';
export const CHANNEL_START_EDITING_CHANNEL = 'CHANNEL_START_EDITING_CHANNEL';

export const SET_EDITOR_OPEN = 'SET_EDITOR_OPEN';

export const UPDATE_CHANNELS = 'UPDATE_CHANNELS';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const SET_NEW_CHANNEL_NAME = 'SET_NEW_CHANNEL_NAME';

