export const DARK_BLUE_CHANNEL_LIST_BACKGROUND = '#02030C';
export const DARK_BLUE_CHANNEL_ITEM_BACKGROUND = '#070919';
export const DARK_BLUE_CHANNEL_FONT = '#575b91';
export const LIGHT_BLUE_HEADER_BACKGROUND = '#dde0fd ';
